In [1]:
!pip3 install xlrd
!pip3 install openpyxl

Collecting xlrd
  Using cached https://files.pythonhosted.org/packages/b0/16/63576a1a001752e34bf8ea62e367997530dc553b689356b9879339cf45a4/xlrd-1.2.0-py2.py3-none-any.whl
Installing collected packages: xlrd
Successfully installed xlrd-1.2.0
Collecting openpyxl
Collecting et-xmlfile (from openpyxl)
Collecting jdcal (from openpyxl)
  Using cached https://files.pythonhosted.org/packages/f0/da/572cbc0bc582390480bbd7c4e93d14dc46079778ed915b505dc494b37c57/jdcal-1.4.1-py2.py3-none-any.whl
Installing collected packages: et-xmlfile, jdcal, openpyxl
Successfully installed et-xmlfile-1.0.1 jdcal-1.4.1 openpyxl-3.0.2

In [2]:
import xlrd
wb = xlrd.open_workbook("./Malegaon.xlsx") 
sheet = wb.sheet_by_index(0)

In [3]:
import pandas as pd
dfs = pd.read_excel("./Malegaon.xlsx",header=[1], sheet_name=None)

In [4]:
cp2018,cp2013,cp2008,cp2003,cp1998 = dfs['CPData-2018'],dfs['CP Data-2013'],dfs['CP Data-2008'],dfs['CP Data-2003'],dfs['CP Data-1998']

In [5]:
cp2018 = cp2018.dropna(how="all")
cp2013 = cp2013.dropna(how="all")
cp2008 = cp2008.dropna(how="all")
cp2003 = cp2003.dropna(how="all")
cp1998 = cp1998.dropna(how="all")

In [6]:
cp2018[0:4]

,Interview Number,Farmer Name,Contact No.,Gat No.,Total Land Holding,Rainfed,Irrigated,पडिक जमीन,खरीप प्रमुख पिके,Area (acres),...,रब्बी प्रमुख पिके,Area (acres).3,रब्बी भाजीपाला पिके,Area (acres).4,उन्हाळी प्रमुख पिके,Area (acres).5,उन्हाळी भाजीपाला पिके,Area (acres).6,वार्षिक व बहुवर्षीय पिके,Area (acres).7
0,1.0,Kamal Vasan Katkade,NaN,NaN,4.0,0.5,3.5,0.0,सोयाबीन,1.5,...,गहू,1.5,NaN,NaN,NaN,NaN,भाजीपाला,1.0,ऊस (आडसाली) - जानेवारी पेरणी,2.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,खरीप भुईमुग,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,Sanket Lakshaman Sangale,9.096649e+09,127.0,2.5,0.0,1.5,1.0,सोयाबीन,1.0,...,गहू,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,खरीप भुईमुग,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
total_land = cp2018['Total Land Holding'].sum()

In [9]:
idx = ['Interview Number','Farmer Name','Contact No.','Gat No.','Total Land Holding','Rainfed','Irrigated','पडिक जमीन','खरीप प्रमुख पिके','Area (acres)','खरीप भाजीपाला पिके','Area (acres)','दीर्घ खरीप पिके','Area (acres)','रब्बी प्रमुख पिके','Area (acres)','रब्बी भाजीपाला पिके','Area (acres)','उन्हाळी प्रमुख पिके','Area (acres)','उन्हाळी भाजीपाला पिके','Area (acres)','वार्षिक व बहुवर्षीय पिके','Area (acres)']

In [10]:
col = ['Interview Number','Farmer Name','Contact No.','Gat No.','Total Land Holding','Rainfed','Irrigated','पडिक जमीन']
cp2018.loc[:,col] = cp2018.loc[:,col].ffill()

/home/tdsc/.local/lib/python3.6/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [11]:
req_col = ['Interview Number','Farmer Name','Total Land Holding','पडिक जमीन','खरीप प्रमुख पिके','Area (acres)','खरीप भाजीपाला पिके','Area (acres)','दीर्घ खरीप पिके','Area (acres)','रब्बी प्रमुख पिके','Area (acres)','रब्बी भाजीपाला पिके','Area (acres)','उन्हाळी प्रमुख पिके','Area (acres)','उन्हाळी भाजीपाला पिके','Area (acres)','वार्षिक व बहुवर्षीय पिके','Area (acres)']
df2018 = cp2018[req_col]

In [13]:
col_names = ['Interview Number','Farmer Name','Total Land Holding','पडिक जमीन','खरीप प्रमुख पिके','area_kharif_major_1','खरीप भाजीपाला पिके','area_kharif_vegi_2','दीर्घ खरीप पिके','area_Kharif_long_3','रब्बी प्रमुख पिके','area_rabi_main_4','रब्बी भाजीपाला पिके','area_rabi_vegi_5','उन्हाळी प्रमुख पिके','area_summer_major_6','उन्हाळी भाजीपाला पिके','area_summer_vegi_7','वार्षिक व बहुवर्षीय पिके','area_annual_8']
df2018.columns = col_names

In [14]:
df2018

,Interview Number,Farmer Name,Total Land Holding,पडिक जमीन,खरीप प्रमुख पिके,area_kharif_major_1,खरीप भाजीपाला पिके,area_kharif_vegi_2,दीर्घ खरीप पिके,area_Kharif_long_3,रब्बी प्रमुख पिके,area_rabi_main_4,रब्बी भाजीपाला पिके,area_rabi_vegi_5,उन्हाळी प्रमुख पिके,area_summer_major_6,उन्हाळी भाजीपाला पिके,area_summer_vegi_7,वार्षिक व बहुवर्षीय पिके,area_annual_8
0,1.0,Kamal Vasan Katkade,4.0,0.0,सोयाबीन,1.50,NaN,1.50,NaN,1.50,गहू,1.50,NaN,1.50,NaN,1.50,भाजीपाला,1.50,ऊस (आडसाली) - जानेवारी पेरणी,1.50
1,1.0,Kamal Vasan Katkade,4.0,0.0,खरीप भुईमुग,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50
3,2.0,Sanket Lakshaman Sangale,2.5,1.0,सोयाबीन,1.00,NaN,1.00,NaN,1.00,गहू,1.00,NaN,1.00,NaN,1.00,NaN,1.00,NaN,1.00
4,2.0,Sanket Lakshaman Sangale,2.5,1.0,खरीप भुईमुग,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50
6,3.0,Yuvraj Keru Avhad,3.0,0.0,सोयाबीन,3.00,NaN,3.00,NaN,3.00,गहू,3.00,NaN,3.00,NaN,3.00,NaN,3.00,NaN,3.00
8,4.0,Prakash Sangale,4.0,0.0,सोयाबीन,4.00,NaN,4.00,NaN,4.00,गहू,4.00,NaN,4.00,NaN,4.00,NaN,4.00,NaN,4.00
10,5.0,Sanjay Kashinath Salve,5.0,0.0,सोयाबीन,5.00,NaN,5.00,NaN,5.00,गहू,5.00,NaN,5.00,NaN,5.00,NaN,5.00,NaN,5.00
12,6.0,Thakuji Shankar Kakade,2.5,0.0,सोयाबीन,2.50,NaN,2.50,NaN,2.50,गहू,2.50,NaN,2.50,NaN,2.50,NaN,2.50,NaN,2.50
14,7.0,Namdev Ramchandra Kakad,15.0,2.0,खरीप भुईमुग,2.00,फुल कोबी,2.00,NaN,2.00,गहू,2.00,कांदा,2.00,NaN,2.00,NaN,2.00,ऊस (पूर्व हंगामी) - ऑक्टोबर,2.00
15,7.0,Namdev Ramchandra Kakad,15.0,2.0,सोयाबीन,4.00,NaN,4.00,NaN,4.00,NaN,4.00,NaN,4.00,NaN,4.00,NaN,4.00,NaN,4.00
17,8.0,Pundalik Kate,8.0,0.0,सोयाबीन,6.00,NaN,6.00,NaN,6.00,गहू,6.00,कांदा,6.00,NaN,6.00,NaN,6.00,NaN,6.00
18,8.0,Pundalik Kate,8.0,0.0,खरीप भुईमुग,1.00,NaN,1.00,NaN,1.00,हरभरा,1.00,NaN,1.00,NaN,1.00,NaN,1.00,NaN,1.00
19,8.0,Pundalik Kate,8.0,0.0,खरीप ज्वारी,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50
20,8.0,Pundalik Kate,8.0,0.0,खरीप चारा पिके,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50,NaN,0.50
22,9.0,Shankar Punja Sangale,3.0,0.0,सोयाबीन,2.75,NaN,2.75,NaN,2.75,गहू,2.75,NaN,2.75,NaN,2.75,NaN,2.75,NaN,2.75
23,9.0,Shankar Punja Sangale,3.0,0.0,खरीप भात,0.25,NaN,0.25,NaN,0.25,NaN,0.25,NaN,0.25,NaN,0.25,NaN,0.25,NaN,0.25
25,10.0,Prakash Sangale,6.0,0.0,सोयाबीन,6.00,NaN,6.00,NaN,6.00,गहू,6.00,NaN,6.00,NaN,6.00,NaN,6.00,NaN,6.00

In [15]:
kharif_1 = ['खरीप ज्वारी','बाजरी','मुग','उडिद','तीळ','सोयाबीन','मका','खरीप भुईमुग','खरीप सुर्यफुल','खरीप चारा पिके','खरीप भात','नागली','वरई','वाल','Others']
kharif_2_ = ['कांदा','मिरची','वांगे','टोमेटो','फुल कोबी','बटाटा','भेंडी','भाजीपाला','Others']
kharif_3 = ['तूर','हळद','आले','कापूस']
rabi_4 = ['रबी ज्वारी','हरभरा','गहू','मका','करडई','मोहोरी','रब्बी इतर गळीत','रबी भुईमुग','रबी सुर्यफुल','रबी चारा पिके','उन्हाळी भुईमुग','उन्हाळी सुर्यफुल','Others']
rabi_5 = ['कांदा','मिरची','वांगे','टोमेटो','फुल कोबी','बटाटा','भेंडी','भाजीपाला']
summer_7 = rabi_5
annual_8 = ['आंबा','काजू','नारळ','सीताफळ','सुपारी','चिकू','पेरू','बोर','द्राक्ष','केळी','डाळिंब','लिंबू वर्गीय झाडे (संत्र, मोसंबी इ.)','ऊस (आडसाली) - जानेवारी पेरणी','ऊस (सुरु) - जानेवारी पेरणी','ऊस (पूर्व हंगामी) - ऑक्टोबर','Others']

In [16]:
df2018.columns

Index(['Interview Number', 'Farmer Name', 'Total Land Holding', 'पडिक जमीन',
       'खरीप प्रमुख पिके', 'area_kharif_major_1', 'खरीप भाजीपाला पिके',
       'area_kharif_vegi_2', 'दीर्घ खरीप पिके', 'area_Kharif_long_3',
       'रब्बी प्रमुख पिके', 'area_rabi_main_4', 'रब्बी भाजीपाला पिके',
       'area_rabi_vegi_5', 'उन्हाळी प्रमुख पिके', 'area_summer_major_6',
       'उन्हाळी भाजीपाला पिके', 'area_summer_vegi_7',
       'वार्षिक व बहुवर्षीय पिके', 'area_annual_8'],
      dtype='object')

In [58]:
k1=df2018.groupby(['खरीप प्रमुख पिके']).agg({
    'area_kharif_major_1':sum,
})
# k1['total_land'] = k1.apply(lambda row: total_land, axis = 1)
if not k1.empty:
    k1['land used/total area'] = k1.apply(lambda row: round(row.area_kharif_major_1/total_land,4), axis = 1) 
k1

                  area_kharif_major_1  land used/total area
खरीप प्रमुख पिके
खरीप चारा पिके                   0.50                0.0094
खरीप ज्वारी                      0.50                0.0094
खरीप भात                         0.25                0.0047
खरीप भुईमुग                      4.00                0.0755
सोयाबीन                         35.75                0.6745

In [57]:
k2=df2018.groupby(['खरीप भाजीपाला पिके']).agg({
    'area_kharif_vegi_2':sum,
})
# k2['total_land'] = k2.apply(lambda row: total_land, axis = 1)
if not k2.empty:
    k2['land used/total area'] = k2.apply(lambda row: round(row.area_kharif_vegi_2/total_land,4), axis = 1) 
k2

                    area_kharif_vegi_2  land used/total area
खरीप भाजीपाला पिके
फुल कोबी                           2.0                0.0377

In [56]:
k3=df2018.groupby(['दीर्घ खरीप पिके']).agg({
    'area_Kharif_long_3':sum,
})
# k3['total_land'] = k3.apply(lambda row: total_land, axis = 1)
if not k3.empty:
    k3['land used/total area'] = k3.apply(lambda row: round(row.area_Kharif_long_3/total_land,4), axis = 1) 
k3

Empty DataFrame
Columns: [area_Kharif_long_3]
Index: []

In [55]:
r4=df2018.groupby(['रब्बी प्रमुख पिके']).agg({
    'area_rabi_main_4':sum,
})
# r4['total_land'] = r4.apply(lambda row: total_land, axis = 1)
if not r4.empty:
    r4['land used/total area'] = r4.apply(lambda row: round(row.area_rabi_main_4/total_land,4), axis = 1) 
r4

                   area_rabi_main_4  land used/total area
रब्बी प्रमुख पिके
गहू                           33.75                0.6368
हरभरा                          1.00                0.0189

In [54]:
r5=df2018.groupby(['रब्बी भाजीपाला पिके']).agg({
    'area_rabi_vegi_5':sum,
})
# r5['total_land'] = r5.apply(lambda row: total_land, axis = 1)
if not r5.empty:
    r5['land used/total area'] = r5.apply(lambda row: round(row.area_rabi_vegi_5/total_land,4), axis = 1) 
r5

                     area_rabi_vegi_5  land used/total area
रब्बी भाजीपाला पिके
कांदा                             8.0                0.1509

In [53]:
s6=df2018.groupby(['उन्हाळी प्रमुख पिके']).agg({
    'area_summer_major_6':sum,
})
# s6['total_land'] = s6.apply(lambda row: total_land, axis = 1)
if not s6.empty:
    s6['land used/total area'] = s6.apply(lambda row: round(row.area_summer_major_6/total_land,4), axis = 1)
s6

Empty DataFrame
Columns: [area_summer_major_6]
Index: []

In [52]:
s7=df2018.groupby(['उन्हाळी भाजीपाला पिके']).agg({
    'area_summer_vegi_7':sum,
})
# s7['total_land'] = s7.apply(lambda row: total_land, axis = 1)
if not s7.empty:
    s7['land used/total area'] = s7.apply(lambda row: round(row.area_summer_vegi_7/total_land,4), axis = 1)
s7

                       area_summer_vegi_7  land used/total area
उन्हाळी भाजीपाला पिके
भाजीपाला                              1.5                0.0283

In [51]:
a8=df2018.groupby(['वार्षिक व बहुवर्षीय पिके']).agg({
    'area_annual_8':sum,
})
# a8['total_land'] = a8.apply(lambda row: total_land, axis = 1)
if not a8.empty:
    a8['land used/total area'] = a8.apply(lambda row: round(row.area_annual_8/total_land,4), axis = 1) 
a8

                              area_annual_8  land used/total area
वार्षिक व बहुवर्षीय पिके
ऊस (आडसाली) - जानेवारी पेरणी            1.5                0.0283
ऊस (पूर्व हंगामी) - ऑक्टोबर             2.0                0.0377

In [48]:
def append_df_to_excel(filename, df, sheet_name='Sheet1', startrow=None,
                       truncate_sheet=False, 
                       **to_excel_kwargs):
    """
    Append a DataFrame [df] to existing Excel file [filename]
    into [sheet_name] Sheet.
    If [filename] doesn't exist, then this function will create it.

    Parameters:
      filename : File path or existing ExcelWriter
                 (Example: '/path/to/file.xlsx')
      df : dataframe to save to workbook
      sheet_name : Name of sheet which will contain DataFrame.
                   (default: 'Sheet1')
      startrow : upper left cell row to dump data frame.
                 Per default (startrow=None) calculate the last row
                 in the existing DF and write to the next row...
      truncate_sheet : truncate (remove and recreate) [sheet_name]
                       before writing DataFrame to Excel file
      to_excel_kwargs : arguments which will be passed to `DataFrame.to_excel()`
                        [can be dictionary]

    Returns: None
    """
    from openpyxl import load_workbook

    import pandas as pd

    # ignore [engine] parameter if it was passed
    if 'engine' in to_excel_kwargs:
        to_excel_kwargs.pop('engine')

    writer = pd.ExcelWriter(filename, engine='openpyxl')

    # Python 2.x: define [FileNotFoundError] exception if it doesn't exist 
    try:
        FileNotFoundError
    except NameError:
        FileNotFoundError = IOError


    try:
        # try to open an existing workbook
        writer.book = load_workbook(filename)

        # get the last row in the existing Excel sheet
        # if it was not specified explicitly
        if startrow is None and sheet_name in writer.book.sheetnames:
            startrow = writer.book[sheet_name].max_row

        # truncate sheet
        if truncate_sheet and sheet_name in writer.book.sheetnames:
            # index of [sheet_name] sheet
            idx = writer.book.sheetnames.index(sheet_name)
            # remove [sheet_name]
            writer.book.remove(writer.book.worksheets[idx])
            # create an empty sheet [sheet_name] using old index
            writer.book.create_sheet(sheet_name, idx)

        # copy existing sheets
        writer.sheets = {ws.title:ws for ws in writer.book.worksheets}
    except FileNotFoundError:
        # file does not exist yet, we will create it
        pass

    if startrow is None:
        startrow = 0

    # write out the new sheet
    df.to_excel(writer, sheet_name, startrow=startrow, **to_excel_kwargs)

    # save the workbook
    writer.save()

In [59]:
k1.to_excel("output.xlsx")
append_df_to_excel("output.xlsx",k2)
append_df_to_excel("output.xlsx",k3)
append_df_to_excel("output.xlsx",r4)
append_df_to_excel("output.xlsx",r5)
append_df_to_excel("output.xlsx",s6)
append_df_to_excel("output.xlsx",s7)
append_df_to_excel("output.xlsx",a8)

53.0